# Generated by Django 5.2.5 on 2025-09-09 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_account_id', models.CharField(max_length=255, unique=True)),
                ('plaid_access_token', models.CharField(max_length=255, null=True, unique=True)),
                ('plaid_item_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=50)),
                ('account_subtype', models.CharField(max_length=50)),
                ('mask', models.CharField(blank=True, max_length=10)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_cursor', models.TextField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['institution_name', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_name', models.CharField(max_length=255)),
                ('authorized_date', models.DateField(null=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='Uncategorized', max_length=100)),
                ('plaid_transaction_id', models.CharField(max_length=255, unique=True)),
                ('plaid_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='plaid_app.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-authorized_date'],
                'indexes': [models.Index(fields=['user', 'authorized_date'], name='plaid_app_t_user_id_412729_idx'), models.Index(fields=['plaid_account_id'], name='plaid_app_t_plaid_a_507a98_idx')],
            },
        ),
    ]
