# Generated by Django 5.2.5 on 2025-09-01 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_account_id', models.CharField(max_length=255, unique=True)),
                ('plaid_transaction_id', models.CharField(max_length=255, unique=True)),
                ('plaid_item_id', models.CharField(blank=True, max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=50)),
                ('account_subtype', models.CharField(max_length=50)),
                ('mask', models.CharField(blank=True, max_length=10)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['institution_name', 'account_name'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='plaid_app.bankaccount'),
        ),
    ]
