# Generated by Django 5.2.5 on 2025-09-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_app', '0002_bankaccount_transaction_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='plaid_access_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
