# Generated by Django 5.2.5 on 2025-09-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_app', '0003_bankaccount_plaid_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='plaid_transaction_id',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='plaid_access_token',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
