# Generated by Django 5.2.5 on 2025-09-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_app', '0004_remove_bankaccount_plaid_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='plaid_item_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
