# Generated by Django 5.2.5 on 2025-08-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryfields',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='entryfields',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
