# Generated by Django 5.2.5 on 2025-08-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetboxuser',
            name='plaid_client_id',
        ),
        migrations.AddField(
            model_name='budgetboxuser',
            name='plaid_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
